# Generated by Django 4.2.2 on 2024-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('bmi', models.FloatField()),
                ('smoker', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=10)),
                ('children', models.IntegerField()),
                ('predicted_insurance_charge', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceData',
        ),
    ]
